### ISSUE TITLE
How to GPU-enable this model.py with backend='gpu'

### ISSUE THREAD

**Issue by pchankh** [anlthms/sp-2016#3]
Hi Anil,

Can the code be enabled to run on GPU? didn't see any gen_backend in code.

Thanks.
Patrick

**Comment by bigsnarfdude** [comment]
Hey Patrick

I just finished running it on a desktop with Ubuntu 14.0.4 and Nvidia GTX 1070 on Intel® Core™ i5-6600K with SSD and it finished under 4 hours.

It used the GPU. I monitor heat and watts consumed during the experiment.

**Comment by anlthms** [comment]
Hi Patrick,
The code automatically picks the GPU if a suitable GPU is available. You'll need an NVIDIA GPU (preferably a Maxwell) with at least 3GB of memory.
Anil
