### ISSUE TITLE
LSTM version of first model per electrode

### ISSUE THREAD

**Issue by bigsnarfdude** [anlthms/sp-2016#6]
Hi Anil,

I created an LSTM version but I'm new to neon so I'm not sure its implemented correctly. 

In comparison to your biRNN  model, do you think there is a significant difference in the two models to pursue optimizing (spending time) the LSTM network?

Here is my code...
https://gist.github.com/bigsnarfdude/cbe9703a2ad1875dbb0e60b9248ced17

**Comment by anlthms** [comment]
Looks correct to me. I don't have any intuition as to which topology is likely to perform better. But I'm pretty sure a BiLSTM would work better than an LSTM.

**Comment by bigsnarfdude** [comment]
Thanks I will refactor and test. Thanks again
