### ISSUE TITLE
Multi-GPU for neon

### ISSUE THREAD

**Issue by bigsnarfdude** [anlthms/sp-2016#7]
Hey Anil,

Is there a flag I can set in --backend mgpu or something to get the project to use both of my GPUs? It uses one ok.  I tried setting -m flag, but I'm wonderig if 

'max number of GPUs (only used with mgpu backend')

is some sort of reserved feature for your product vs open source release. can you comment?

**Comment by anlthms** [comment]
You're right. Multi-GPU is a reserved feature for now.
