### ISSUE TITLE
import util - file not found

### ISSUE THREAD

**Issue by bigsnarfdude** [anlthms/sp-2016#8]
```
from util import auc, avg, avg_preds
from util import score
```

I'm having trouble finding where the `util` file is located? 
What package is it from? 
Can you share the 4 functions?

**Comment by bigsnarfdude** [comment]
im guessing this might be four of the missing functions?
```
auc = metrics.roc_auc_score(labels, preds)
score = metrics.accuracy_score(labels, preds)   ???
avg = metrics.average_precision_score(labels, preds)   ???
avg_preds = ???
```

**Comment by anlthms** [comment]
Thanks for reporting this! I have uploaded the missing file.
